/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlinereservationapp;

import Controller.MaskapaiController;
import Model.User;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reistein
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private User user;
    
    public MainForm(User user) {
        initComponents();
        this.user = user;
        
        Page_TikSay.setVisible(false);
        Page_Akun.setVisible(false);
        
        this.tampildata();
    }

    public void tampildata() {
        MaskapaiController mc = new MaskapaiController();
        DefaultTableModel dtm = mc.createtable();
        
        this.tbl_pemesanan.setModel(dtm);
        
        mc.tampilkanPenerbangan();
        
        Txt_Name.setText(user.getName());
        Txt_Uname.setText(user.getUsername());
        Txt_Email.setText(user.getEmail());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Tab_PemTik = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tab_TikSay = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Tab_Akun = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Page_PemTik = new javax.swing.JPanel();
        Tujuan_Penerbangan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tgl_Penerbangan = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        Maskapai_Penerbangan = new javax.swing.JComboBox<>();
        Btn_Cari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_pemesanan = new javax.swing.JTable();
        Btn_Pesan = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Btn_Reset = new javax.swing.JButton();
        Page_TikSay = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tiketsy = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        Page_Akun = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Txt_Name = new javax.swing.JTextField();
        Txt_Uname = new javax.swing.JTextField();
        Txt_Email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Halim Domestik Air");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab_PemTik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_PemTik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_PemTikMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pemesanan Tiket");

        javax.swing.GroupLayout Tab_PemTikLayout = new javax.swing.GroupLayout(Tab_PemTik);
        Tab_PemTik.setLayout(Tab_PemTikLayout);
        Tab_PemTikLayout.setHorizontalGroup(
            Tab_PemTikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_PemTikLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Tab_PemTikLayout.setVerticalGroup(
            Tab_PemTikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_PemTikLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab_TikSay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_TikSay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_TikSayMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tiket Saya");

        javax.swing.GroupLayout Tab_TikSayLayout = new javax.swing.GroupLayout(Tab_TikSay);
        Tab_TikSay.setLayout(Tab_TikSayLayout);
        Tab_TikSayLayout.setHorizontalGroup(
            Tab_TikSayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_TikSayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Tab_TikSayLayout.setVerticalGroup(
            Tab_TikSayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_TikSayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab_Akun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_Akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_AkunMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Akun");

        javax.swing.GroupLayout Tab_AkunLayout = new javax.swing.GroupLayout(Tab_Akun);
        Tab_Akun.setLayout(Tab_AkunLayout);
        Tab_AkunLayout.setHorizontalGroup(
            Tab_AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_AkunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Tab_AkunLayout.setVerticalGroup(
            Tab_AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_AkunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(Tab_PemTik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tab_TikSay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tab_Akun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Tab_PemTik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Tab_TikSay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addComponent(Tab_Akun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        Tujuan_Penerbangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Tujuan Anda --", "Surabaya (Juanda Airport)", "Yogyakarta (Adi Sujipto Airport)", "Medan (Kualanamu Airport)", "Malang (Abdul Rachman Saleh Airport)", "Padang (Minangkabau Airport)", "Bali (Ngurah Rai Airport)" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tujuan Penerbangan");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tanggal Penerbangan");

        Tgl_Penerbangan.setDateFormatString("yyyy-MM-dd");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Maskapai Penerbangan");

        Maskapai_Penerbangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Maskapai Penerbangan --", "CITILINK INDONESIA", "GARUDA INDONESIA", "BATIK AIR" }));
        Maskapai_Penerbangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Maskapai_PenerbanganActionPerformed(evt);
            }
        });

        Btn_Cari.setText("Cari");
        Btn_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CariActionPerformed(evt);
            }
        });

        tbl_pemesanan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbl_pemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_pemesanan.setRowHeight(30);
        jScrollPane2.setViewportView(tbl_pemesanan);

        Btn_Pesan.setText("Pesan Tiket");
        Btn_Pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PesanActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setText("Pemesanan Tiket");

        Btn_Reset.setText("Reset");
        Btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Page_PemTikLayout = new javax.swing.GroupLayout(Page_PemTik);
        Page_PemTik.setLayout(Page_PemTikLayout);
        Page_PemTikLayout.setHorizontalGroup(
            Page_PemTikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Page_PemTikLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(351, 351, 351))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Page_PemTikLayout.createSequentialGroup()
                .addGroup(Page_PemTikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Page_PemTikLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Page_PemTikLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(Page_PemTikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(Page_PemTikLayout.createSequentialGroup()
                                .addGroup(Page_PemTikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(Page_PemTikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Tujuan_Penerbangan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Maskapai_Penerbangan, 0, 262, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                .addGroup(Page_PemTikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Page_PemTikLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Tgl_Penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Page_PemTikLayout.createSequentialGroup()
                                        .addComponent(Btn_Reset)
                                        .addGap(18, 18, 18)
                                        .addComponent(Btn_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(50, 50, 50))
        );
        Page_PemTikLayout.setVerticalGroup(
            Page_PemTikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Page_PemTikLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(29, 29, 29)
                .addGroup(Page_PemTikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(Tgl_Penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tujuan_Penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Page_PemTikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Maskapai_Penerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Cari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Reset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        tbl_tiketsy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbl_tiketsy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_tiketsy.setRowHeight(30);
        jScrollPane1.setViewportView(tbl_tiketsy);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("Tiket Saya");

        javax.swing.GroupLayout Page_TikSayLayout = new javax.swing.GroupLayout(Page_TikSay);
        Page_TikSay.setLayout(Page_TikSayLayout);
        Page_TikSayLayout.setHorizontalGroup(
            Page_TikSayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Page_TikSayLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(Page_TikSayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Page_TikSayLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Page_TikSayLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(407, 407, 407))))
        );
        Page_TikSayLayout.setVerticalGroup(
            Page_TikSayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Page_TikSayLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("AKUN SAYA");

        jLabel11.setText("Nama           :");

        jLabel12.setText("Username    :");

        jLabel13.setText("Email            :");

        Txt_Name.setEditable(false);
        Txt_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NameActionPerformed(evt);
            }
        });

        Txt_Uname.setEditable(false);

        Txt_Email.setEditable(false);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Page_AkunLayout = new javax.swing.GroupLayout(Page_Akun);
        Page_Akun.setLayout(Page_AkunLayout);
        Page_AkunLayout.setHorizontalGroup(
            Page_AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Page_AkunLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(Page_AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(28, 28, 28)
                .addGroup(Page_AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Page_AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Txt_Name)
                        .addComponent(Txt_Uname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Page_AkunLayout.createSequentialGroup()
                .addContainerGap(403, Short.MAX_VALUE)
                .addGroup(Page_AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Page_AkunLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(387, 387, 387))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Page_AkunLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(34, 34, 34))))
        );
        Page_AkunLayout.setVerticalGroup(
            Page_AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Page_AkunLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(41, 41, 41)
                .addGroup(Page_AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Page_AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Txt_Uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Page_AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Page_PemTik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Page_TikSay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Page_Akun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Page_PemTik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Page_TikSay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Page_Akun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tab_PemTikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_PemTikMouseClicked
        // TODO add your handling code here:
        Page_PemTik.setVisible(true);
        tbl_pemesanan.setVisible(true);
        Page_TikSay.setVisible(false);
        Page_Akun.setVisible(false);
        
    }//GEN-LAST:event_Tab_PemTikMouseClicked

    private void Tab_TikSayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_TikSayMouseClicked
        // TODO add your handling code here:
        Page_PemTik.setVisible(false);
        tbl_pemesanan.setVisible(false);
        Page_TikSay.setVisible(true);
        Page_Akun.setVisible(false);
    }//GEN-LAST:event_Tab_TikSayMouseClicked

    private void Tab_AkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_AkunMouseClicked
        // TODO add your handling code here:
        
        Page_PemTik.setVisible(false);
        tbl_pemesanan.setVisible(false);
        Page_TikSay.setVisible(false);
        Page_Akun.setVisible(true);
    }//GEN-LAST:event_Tab_AkunMouseClicked

    private void Maskapai_PenerbanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Maskapai_PenerbanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Maskapai_PenerbanganActionPerformed

    private void Btn_PesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_PesanActionPerformed

    private void Txt_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NameActionPerformed

    private void Btn_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CariActionPerformed
        // TODO add your handling code here:
        String ftgl ="yyyy-MM-dd";
        
        SimpleDateFormat fm = new SimpleDateFormat(ftgl);
        
        String TujuanSelect = Tujuan_Penerbangan.getSelectedItem().toString();
        String MaskapaiSelect = Maskapai_Penerbangan.getSelectedItem().toString();
        String Tgl = String.valueOf(fm.format(Tgl_Penerbangan.getDate()));
        
        String Tujuan = "";
        if (TujuanSelect.equals("Surabaya (Juanda Airport)")){
            Tujuan = "Juanda Airport";
            
        } else if (TujuanSelect.equals("Yogyakarta (Adi Sujipto Airport)")) {
            Tujuan = "Adi Sujipto Airport";
            
        } else if (TujuanSelect.equals("Medan (Kualanamu Airport)")) {
            Tujuan = "Kualanamu Airport";
            
        } else if (TujuanSelect.equals("Malang (Abdul Rachman Saleh Airport)")) {
            Tujuan = "Abdul Rachman Saleh Airport";
            
        } else if (TujuanSelect.equals("Padang (Minangkabau Airport)")) {
            Tujuan = "Minangkabau Airport";
            
        } else if (TujuanSelect.equals("Bali (Ngurah Rai Airport)")) {
            Tujuan = "Ngurah Rai Airport";
            
        } else {
            Tujuan = "";
        }
        
        String Maskapai = "";
        if (MaskapaiSelect.equals("-- Pilih Maskapai Penerbangan --")){
            Maskapai = "";
        } else {
            Maskapai = MaskapaiSelect;
        }
        
        try{
            MaskapaiController mc = new MaskapaiController();
            DefaultTableModel dtm = mc.createtable();
        
            this.tbl_pemesanan.setModel(dtm);
        
            //mc.tampilkanPenerbangan();
            mc.cariTiket(Tujuan, Maskapai, Tgl);
        } catch (Exception e) {
            System.out.println(e + "\n Error filter");
        }
    }//GEN-LAST:event_Btn_CariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ResetActionPerformed
        // TODO add your handling code here:
        Tujuan_Penerbangan.setSelectedIndex(0);
        Maskapai_Penerbangan.setSelectedIndex(0);
        Tgl_Penerbangan.setDate(null);
        
        MaskapaiController mc = new MaskapaiController();
        DefaultTableModel dtm = mc.createtable();
        
        this.tbl_pemesanan.setModel(dtm);
        
        mc.tampilkanPenerbangan();
    }//GEN-LAST:event_Btn_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cari;
    private javax.swing.JButton Btn_Pesan;
    private javax.swing.JButton Btn_Reset;
    private javax.swing.JComboBox<String> Maskapai_Penerbangan;
    private javax.swing.JPanel Page_Akun;
    private javax.swing.JPanel Page_PemTik;
    private javax.swing.JPanel Page_TikSay;
    private javax.swing.JPanel Tab_Akun;
    private javax.swing.JPanel Tab_PemTik;
    private javax.swing.JPanel Tab_TikSay;
    private com.toedter.calendar.JDateChooser Tgl_Penerbangan;
    private javax.swing.JComboBox<String> Tujuan_Penerbangan;
    private javax.swing.JTextField Txt_Email;
    private javax.swing.JTextField Txt_Name;
    private javax.swing.JTextField Txt_Uname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_pemesanan;
    private javax.swing.JTable tbl_tiketsy;
    // End of variables declaration//GEN-END:variables
}
